OnlineAppointmentPanel/Controllers/AppointmentsController.cs
using Entities.DTOs.Appointment;
using Entities.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.AppServices.AppointmentServices;
using Services.AppServices.ServiceServices;
using Services.Constansts;
using System.Security.Claims;

namespace OnlineAppointmentPanel.Controllers
{
    [Authorize]
    public class AppointmentsController : Controller
    {
        private readonly IAppointmentService _appointmentService;
        private readonly IServiceService _serviceService;        

        public AppointmentsController(IAppointmentService appointmentService, IServiceService serviceService)
        {
            _appointmentService = appointmentService;
            _serviceService = serviceService;           
        }

        [Authorize(Roles = nameof(UserRoles.Admin) + "," + nameof(UserRoles.Customer))]
        public async Task<IActionResult> Index()
        {
            var result = await _appointmentService.GetAppointmentsForUserAsync();
            if (!result.IsSuccess)
            {
                ViewBag.ErrorMessage = string.Join(",", result.ErrorMessage);
                return View();
            }
            ViewBag.IsCustomer = result.Data.IsCustomer;
            ViewBag.IsAdmin = result.Data.IsAdmin;
            return View(result.Data);
        }

        [HttpGet]
        [Route("Appointments/GetById/{id}")]
        public async Task<JsonResult> GetById(Guid id)
        {
            var result = await _appointmentService.GetByIdAsync(id);
            if (result.IsSuccess)
            {
                return Json(new
                {
                    success = true,                    
                    data = result.Data
                });
            }

            return Json(new
            {
                success = false,
                message = Messages.NotFound,
            });

        }

        [HttpGet]
        [Route("Appointments/Detail/{id}")]
        public async Task<IActionResult> Detail([FromRoute] Guid id)
        {
            var result = await _appointmentService.GetByIdAsync(id);

            if (result.IsSuccess && result.Data != null)
            {
                return View(result.Data);
            }

            ViewBag.ErrorMessage = string.Join(",", result.ErrorMessage);
            return View("Error");
        }

        [HttpGet]
        [Route("Appointments/GetServices")]
        public async Task<IActionResult> GetServices()
        {
            var result = await _serviceService.Where(s => s.IsDelete == false);
            if (result.IsSuccess && result.Data != null)
            {
                var services = result.Data.Select(s => new
                {
                    id = s.Id,
                    name = s.Name
                }).ToList();

                return Json(new { success = true, services });
            }

            return Json(new { success = false, errorMessage = Messages.ServicesCouldNotBeLoaded });
        }

        [HttpGet]
        public IActionResult GetStatuses()
        {
            var statuses = Enum.GetValues(typeof(AppointmentStatus))
                .Cast<AppointmentStatus>()
                .Where(status => status != AppointmentStatus.Unknown)
                .Select(status => new
                {
                    Id = (int)status,
                    Name = status.ToString()
                }).ToList();

            return Json(new { success = true, statuses });
        }

        [Authorize(Roles = nameof(UserRoles.Customer))]
        [HttpPost]
        public async Task<IActionResult> Create(CreateAppointmentRequest request)
        {
            if (!ModelState.IsValid)
                return Json(new { success = false, errorMessage = string.Join("; ", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList()) });

            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;            
            request.UserId = Guid.Parse(userIdClaim);

            var result = await _appointmentService.CreateAsync(request);
            if (result.IsSuccess)
            {
                var createdAppointment = result.Data;
                return Json(new
                {
                    success = true,
                    message = Messages.AppointmentHasBeenCreated,
                    appointment = new
                    {
                        Id = createdAppointment.Id,
                        UserName = User.Identity.Name,
                        ServiceName = createdAppointment.ServiceName,
                        AppointmentDate = createdAppointment.AppointmentDate.ToString("yyyy-MM-dd HH:mm"),
                        Status = createdAppointment.Status.ToString()
                    }
                });
            }
            return Json(new { success = false, errorMessage = string.Join(",", result.ErrorMessage) });
        }

        [Authorize(Roles = nameof(UserRoles.Customer))]
        [HttpPost]
        public async Task<JsonResult> Update(UpdateAppointmentRequest request)
        {
            if (!ModelState.IsValid)
                return Json(new { success = false, errorMessage = string.Join("; ", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList()) });

            var originalData = await _appointmentService.GetByIdAsync(request.Id);  
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (User.IsInRole(nameof(UserRoles.Customer)) &&
                (userIdClaim == null || originalData.Data.UserId.ToString() != userIdClaim))
            {
                return Json(new { success = false, errorMessage = Messages.YouAreNotAuthorizedToUpdateThisAppointment });
            }

            if (originalData.Data.Status != AppointmentStatus.Pending)
            {
                return Json(new { success = false, errorMessage = Messages.YouCanOnlyUpdateYourPendingAppointments });
            }
            request.Status = AppointmentStatus.Pending;
            var result = await _appointmentService.UpdateAsync(request);
            if (result.IsSuccess)
            {
                var updatedAppointment = result.Data;
                return Json(new
                {
                    success = true,
                    message = Messages.AppointmentUpdatedSuccessfully,
                    appointment = new
                    {
                        Id = updatedAppointment.Id,
                        UserName = User.Identity.Name,
                        UserId = updatedAppointment.UserId,
                        ServiceName = updatedAppointment.ServiceName,
                        AppointmentDate = updatedAppointment.AppointmentDate.ToString("yyyy-MM-dd HH:mm"),
                        Status = updatedAppointment.Status.ToString()
                    }
                });
            }
            return Json(new { success = false, errorMessage = string.Join(",", result.ErrorMessage) });
        }

        [Authorize(Roles = nameof(UserRoles.Admin))]
        [HttpPost]
        public async Task<IActionResult> UpdateStatus(UpdateAppointmentStatusRequest request)
        {
            if (!ModelState.IsValid)
                return Json(new { success = false, errorMessage = string.Join("; ", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList()) });

            var result = await _appointmentService.UpdateStatusAsync(request);
            if (result.IsSuccess)
            {
                return Json(new
                {
                    success = true,
                    message = Messages.StatusUpdatedSuccessfully,
                    appointment = new
                    {
                        id = result.Data.Id,
                        status = result.Data.Status
                    }
                });
            }
            return Json(new { success = false, errorMessage = result.ErrorMessage });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _appointmentService.SoftDeleteAsync(id);

            if (result.IsSuccess)
            {
                return Json(new { success = true, message = Messages.AppointmentDeletedSuccessfully, id = id });
            }
            return Json(new { success = false, errorMessage = string.Join(",", result.ErrorMessage) });
        }
    }
}

OnlineAppointmentPanel/Controllers/UsersController.cs
using Entities.DTOs.Auth;
using Entities.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.AppServices.UserServices;
using Services.Constansts;

namespace OnlineAppointmentPanel.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly IUserService _userService;
        

        public UsersController(IUserService userService)
        {
            _userService = userService;           
        }

        [Authorize(Roles = nameof(UserRoles.Admin))]
        public async Task<IActionResult> Index()      
        {
            var result = await _userService.GetAll();
            if (result.IsSuccess)
            {
                return View(result.Data);
            }
            return View("Error", result.ErrorMessage);
        }

        [Authorize(Roles = nameof(UserRoles.Admin) + "," + nameof(UserRoles.Customer))]
        public async Task<IActionResult> Detail(Guid id)
        {
            var result = await _userService.GetByIdAsync(id);
            if (result.IsSuccess)
            {
                return View(result.Data);
            }
            return View("Error", result.ErrorMessage);
        }

        [Authorize(Roles = nameof(UserRoles.Admin))]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = nameof(UserRoles.Admin))]
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var result = await _userService.CreateAsync(request);
            if (result.IsSuccess)
            {
                return RedirectToAction("Index");
            }

            ModelState.AddModelError(string.Empty, string.Join(",", result.ErrorMessage));
            return View(request);
        }

        [Authorize(Roles = nameof(UserRoles.Admin))]
        [HttpDelete]
        [Route("/Users/Delete/{id}")]
        public async Task<IActionResult> Delete([FromRoute] Guid id)
        {
            var result = await _userService.SoftDeleteAsync(id);
            if (result.IsSuccess)
            {
                return Json(new { success = true, message = Messages.UserDeletedSuccessfully });
            }
            return Json(new { success = false, errorMessage = result.ErrorMessage });
        }

        [Authorize(Roles = nameof(UserRoles.Admin))]
        [HttpPost]
        public async Task<IActionResult> SoftDelete(Guid id)
        {
            var result = await _userService.SoftDeleteAsync(id);
            if (result.IsSuccess)
            {
                return RedirectToAction("Index");
            }
            return View("Error", result.ErrorMessage);
        }

        [Authorize(Roles = nameof(UserRoles.Admin))]
        [HttpGet]
        public async Task<IActionResult> AssignRole(Guid id)
        {
            var result = await _userService.GetByIdAsync(id);
            if (!result.IsSuccess || result.Data == null)
            {
                return View("Error", result.ErrorMessage);
            }

            var assignedRoles = result.Data.Roles;

            var model = new AssignRoleRequest
            {
                UserId = id,
                AvailableRoles = Enum.GetValues(typeof(UserRoles))
                                     .Cast<UserRoles>()
                                     .Where(role => role != UserRoles.Unknown)
                                     .Select(role => new RoleDto
                                     {
                                         Id = (int)role,
                                         Name = role.ToString()
                                     })
                                     .ToList(),

                AssignedRoles = assignedRoles.Select(r => new RoleDto
                {
                    Id = (int)r,
                    Name = r.ToString()
                }).ToList()
            };

            return View(model);
        }

        [Authorize(Roles = nameof(UserRoles.Admin))]
        [HttpPost]
        public async Task<IActionResult> AssignRole(AssignRoleRequest request)
        {
            if (!ModelState.IsValid)
            {
                request.AvailableRoles = Enum.GetValues(typeof(UserRoles))
                                              .Cast<UserRoles>()
                                              .Where(role => role != UserRoles.Unknown)
                                              .Select(role => new RoleDto
                                              {
                                                  Id = (int)role,
                                                  Name = role.ToString()
                                              })
                                              .ToList();

                return View(request);
            }

            var userResult = await _userService.GetByIdAsync(request.UserId);
            if (!userResult.IsSuccess || userResult.Data == null)
            {
                ModelState.AddModelError(string.Empty, Messages.UserInformationNotRetrieved);
                return View(request);
            }

            if (userResult.Data.Roles.Contains(request.SelectedRole))
            {
                TempData["ErrorMessage"] = Messages.RoleAlreadyAssigned;
                return RedirectToAction("AssignRole", new { id = request.UserId });
            }

            var result = await _userService.AssignRoleAsync(request.UserId, request.SelectedRole);
            if (result.IsSuccess)
            {
                TempData["SuccessMessage"] = Messages.RoleAssignedSuccessfully;
                return RedirectToAction("Index");
            }

            ModelState.AddModelError(string.Empty, string.Join(",", result.ErrorMessage));
            return View(request);
        }

        [Authorize(Roles = nameof(UserRoles.Admin))]
        [HttpPost]
        public async Task<IActionResult> RemoveRole(Guid userId, UserRoles role)
        {
            var removeRoleResult = await _userService.RemoveRoleAsync(userId, role);
            if (removeRoleResult.IsSuccess)
            {
                TempData["SuccessMessage"] = Messages.RoleRemovedSuccessfully;
            }
            else
            {
                TempData["ErrorMessage"] = removeRoleResult.ErrorMessage;
            }
            return RedirectToAction("AssignRole", new { id = userId });
        }
    }
}

OnlineAppointmentPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dinçer Online Randevu Sistemi</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.20/dist/sweetalert2.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">    
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <style>       
       
        footer {
            background-color: #f8f9fa;
            padding: 20px 0;
            text-align: center;
            font-size: 14px;
            border-top: 1px solid #ddd;
        }
    </style>
</head>
<body class="d-flex flex-column" style="min-height:100svh; margin-bottom:0 !important">
    <header>
        <div class="navbar navbar-expand-lg shadow-sm bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="/Home/Index">
                    <img src="~/images/logo/logo.png" alt="Logo" width="100" class="d-inline-block align-text-top">
                    <label> Online Randevu ve Yönetim Sistemi </label>
                </a>                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <nav class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav ms-auto fw-bold ">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Appointments" asp-action="Index">Randevular</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Index">Kullanıcılar</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-person-circle"></i> @User.Identity.Name
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                                    <li><a class="dropdown-item" asp-controller="Auth" asp-action="Logout">Çıkış</a></li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Login">Giriş Yap</a>
                            </li>
                        }
                    </ul>
                </nav>
            </div>
        </div>

    </header>
    <div class="container my-4">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="mt-auto" >
        <div class="container">
            &copy; 2024 Dinçer Online Randevu ve Yönetim Sistemi. Tüm Hakları Saklıdır.
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.7/umd/popper.min.js"></script>       
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>